import type { Metadata } from 'next';
import Script from 'next/script';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <Script src='https://cdn.cloud.pspdfkit.com/pspdfkit-web@1.3.0/nutrient-viewer.js' strategy='beforeInteractive' />
      </head>
      <body>{children}</body>
    </html>
  );
}
